apiVersion: apps/v1
kind: Deployment
metadata:
  name: medicure-app-deployment
spec:
  selector:
    matchLabels:
      app: medicure-app
  replicas: 3
  template:
    metadata:
      labels:
        app: medicure-app
    spec:
      containers:
      - name: medicure-app
        image: rahul9711/medicure:1.0
        imagePullPolicy: Always
        ports:
        - name: medicure-app
          containerPort: 8082
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: medicure-app-service
  labels:
    app: medicure-app
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
  - port: 8082
  selector:
    app: medicure-app
